[package]
name = "maze_env_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "maze_env_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.24.0"
rand = "0.9.1"
